name: FancyClicker
version: '${project.version}'
main: com.lmcstudios.fancyclicker.FancyClickerPlugin
api-version: '26.1.2'
author: lmc Studios
description: Ein moderner Cookie-Clicker fuer deinen Minecraft-Server.
softdepend: [Vault, PlaceholderAPI]

commands:
  fc:
    description: Hauptbefehl von FancyClicker.
    usage: /fc <bind|unbind|reload|reset|setcookie|addcookie|setlevel>
    aliases: [fancyclicker]

permissions:
  fancyclicker.use:
    description: Erlaubt das Benutzen des Cookie-Clicker-Blocks.
    default: true
  fancyclicker.admin:
    description: Erlaubt Admin-Befehle.
    default: op